select
audit.USERID,
audit.REPORTID,
CASE WHEN audit.CREATEDPUB = 1 THEN 1 ELSE 0 END AS CREATEDPUB_NUM,
CASE WHEN audit.REFRESHEDDATA = 1 THEN 1 ELSE 0 END AS REFRESHEDDATA_NUM,
reports.REPORTNAME,
reports.DESCRIPTION,
CONVERT(DATETIME, FLOOR(CONVERT(FLOAT, audit.REQUESTTIME))) as REQUEST_DATE,
DATEDIFF(SECOND, audit.REQUESTTIME, audit.PROCESSTIME) as PROCESS_TIME_SEC
from
[LawsonRS].[dbo].[RS_AUDIT] audit
join
LawsonRS.dbo.ERS_REPORTS reports
on reports.REPORTID = audit.REPORTID
